application.jab=.\\conf
application.racine=.\\conf
application.jeu.regions.types=terrestre;maritime;capitale
application.jeu.regions.types.carte=.\\conf\\textures\\monde\\carte_types_regions.csv
application.jeu.regions.terrestre.code=T
application.jeu.regions.maritime.code=M
application.jeu.regions.capitale.code=C
application.jeu.regions.alignements.carte=.\\conf\\textures\\monde\\carte_alignements_regions.csv
application.jeu.civilisations=rome;carthage
application.jeu.civilisations.rome.code=R
application.jeu.civilisations.rome.nom=Rome
application.jeu.civilisations.rome.unites.types=soldat;general;catapulte
application.jeu.civilisations.rome.unites.soldat.libelle=Soldat
application.jeu.civilisations.rome.unites.general.libelle=Général
application.jeu.civilisations.rome.unites.catapulte.libelle=Cataplute
application.jeu.civilisations.rome.unites.soldat.maximum=120
application.jeu.civilisations.rome.unites.general.maximum=6
application.jeu.civilisations.rome.unites.catapulte.maximum=4
application.jeu.civilisations.rome.unites.soldat.vie=3
application.jeu.civilisations.rome.unites.general.vie=12
application.jeu.civilisations.rome.unites.catapulte.vie=20
application.jeu.civilisations.rome.unites.soldat.force=1
application.jeu.civilisations.rome.unites.general.force=4
application.jeu.civilisations.rome.unites.catapulte.force=10
application.jeu.civilisations.rome.unites.soldat.praticables=T
application.jeu.civilisations.rome.unites.general.praticables=T
application.jeu.civilisations.rome.unites.catapulte.praticables=T
application.jeu.civilisations.rome.transports.types=bateau
application.jeu.civilisations.rome.transports.bateau.praticables=M
application.jeu.civilisations.rome.transports.bateau.texture=0;1
application.jeu.civilisations.rome.transports.bateau.libelle=Bateau
application.jeu.civilisations.rome.transports.bateau.maximum=10
application.jeu.civilisations.rome.capitale=6;20
application.jeu.civilisations.rome.armees.types=legion
application.jeu.civilisations.rome.armees.legion.libelle=Légion
application.jeu.civilisations.rome.armees.legion.texture=0;0
application.jeu.civilisations.rome.armees.legion.maximum=12
application.jeu.civilisations.carthage.code=C
application.jeu.civilisations.carthage.nom=Carthage
application.jeu.civilisations.carthage.unites.types=soldat;general;catapulte;elephant
application.jeu.civilisations.carthage.unites.soldat.libelle=Soldat
application.jeu.civilisations.carthage.unites.general.libelle=Général
application.jeu.civilisations.carthage.unites.catapulte.libelle=Cataplute
application.jeu.civilisations.carthage.unites.elephant.libelle=Elephant
application.jeu.civilisations.carthage.unites.soldat.maximum=120
application.jeu.civilisations.carthage.unites.general.maximum=6
application.jeu.civilisations.carthage.unites.catapulte.maximum=4
application.jeu.civilisations.carthage.unites.elephant.maximum=4
application.jeu.civilisations.carthage.unites.soldat.vie=3
application.jeu.civilisations.carthage.unites.general.vie=12
application.jeu.civilisations.carthage.unites.catapulte.vie=20
application.jeu.civilisations.carthage.unites.elephant.vie=20
application.jeu.civilisations.carthage.unites.soldat.force=1
application.jeu.civilisations.carthage.unites.general.force=4
application.jeu.civilisations.carthage.unites.catapulte.force=10
application.jeu.civilisations.carthage.unites.elephant.force=10
application.jeu.civilisations.carthage.unites.soldat.praticables=T
application.jeu.civilisations.carthage.unites.general.praticables=T
application.jeu.civilisations.carthage.unites.catapulte.praticables=T
application.jeu.civilisations.carthage.unites.elephant.praticables=T
application.jeu.civilisations.carthage.transports.types=bateau
application.jeu.civilisations.carthage.transports.bateau.praticables=M
application.jeu.civilisations.carthage.transports.bateau.texture=1;1
application.jeu.civilisations.carthage.transports.bateau.libelle=Bateau
application.jeu.civilisations.carthage.transports.bateau.maximum=10
application.jeu.civilisations.carthage.capitale=12;18
application.jeu.civilisations.carthage.armees.types=legion
application.jeu.civilisations.carthage.armees.legion.libelle=Légion
application.jeu.civilisations.carthage.armees.legion.texture=1;0
application.jeu.civilisations.carthage.armees.legion.maximum=12
application.jeu.cadrillage.taille=24;36;4320;2880
application.jeu.jetons.taille=2;2;128;128
application.ombrages=case:activer#vecteur:fragment#projection:vision:transformation:echantillonneur,\
  case:survoler#vecteur:fragment#projection:vision:transformation:echantillonneur,\
  jeton:base#vecteur:fragment#projection:vision:transformation:echantillonneur,\
  jeton:activer#vecteur:fragment#projection:vision:transformation:echantillonneur