jab.base=.\\base
jab.sauvegarde.nombre.threads=10
jab.sauvegarde.asynchrone=false
jab.sauvegarde.delai=5000
jab.sources=parties:org.mgd.guerres.puniques.coeur.source.PartieAd,\
  registre:org.mgd.guerres.puniques.coeur.source.RegistreAd
jab.persistences=partie:org.mgd.guerres.puniques.coeur.persistence.PartieJao,\
  registre:org.mgd.guerres.puniques.coeur.persistence.RegistreJao
