appender.0.type=Console
appender.0.name=CONSOLE
appender.0.layout.type=PatternLayout
appender.0.layout.pattern=%d{yyyy-MM-dd HH:mm:ss} %p %m%n
appender.1.type=RollingFile
appender.1.name=PRINCIPAL
appender.1.fileName=logs/guerres-puniques.log
appender.1.filePattern=logs/guerres-puniques.%d{yyyy-MM-dd}.%i.log
appender.1.layout.type=PatternLayout
appender.1.layout.pattern=%d{yyyy-MM-dd HH:mm:ss} %p %m%n
appender.1.policy.type=Policies
appender.1.policy.0.type=OnStartupTriggeringPolicy
appender.1.policy.1.type=SizeBasedTriggeringPolicy
appender.1.policy.2.type=TimeBasedTriggeringPolicy
rootLogger.level=ALL
rootLogger.appenderRef.0.ref=CONSOLE
rootLogger.appenderRef.1.ref=PRINCIPAL
